services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${FAPI_TMPL_BUILD_TARGET:-production}
    ports:
      - "${FAPI_TMPL_BIND_IP:-0.0.0.0}:${FAPI_TMPL_BIND_PORT:-8000}:8000"
    env_file:
      - .env
